spring:
  application:
    name: url-shortener

  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: VAULT-TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: url-shortener-database

  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091
